### ISSUE TITLE
Any plans to support .NET 6

### ISSUE THREAD

**Issue by CarlSargunar** [braintree/braintree_dotnet#118]
With the recent release of .NET 6, and given this is a multi-targeted library what are the plans to support the latest version? Would be great to see a version built for .NET 6

**Comment by Epreuve** [comment]
Hey @CarlSargunar 

We're definitely going to take a look and make sure the SDK works with the newest released .Net versions.  In the mean time, was there a specific issue you're seeing when attempting to use it with .Net 6, or was there a specific feature you were hoping we would add support for?

**Comment by smendoza88** [comment]
Hey @Epreuve 

To follow up with what @CarlSargunar said, .Net 3.1 EOL is Dec 3, 2022 https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core. 

I have not updated our app from 3.1 to 6 that uses Braintree. I was hoping we would have a timeline of when Braintree would be supporting .Net 6.

**Comment by glenn2223** [comment]
>I have not updated our app from 3.1 to 6 that uses Braintree.

@smendoza88: As it supports `netstandard2.0` it will work in .NET 6 (I use it myself, so can confirm it definitely works). If they plan to continue to support .NET Framework (btw 4.5.2 is [EOL on April 26, 2022](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net452#:~:text=This%20version%20of%20.NET%20Framework%20will%20reach%20end%20of%20support%20on%20April%2026%2C%202022)) then they will always target (up to) `net48` and `netstandard2`

Ps. thanks for the package guys!

**Comment by hollabaq86** [comment]
👋  Happy EOL day! I want to give a little clarity on our support for server language versions.

Any decisions on our part to _drop_ support will only happen as part of a major version update to the SDK (see our [deprecation policy](https://developer.paypal.com/braintree/docs/reference/general/server-sdk-deprecation-policy) for details).

When it comes to supporting new versions, what @glenn2223 commented is correct, we do our best to support as many versions as possible via .NET's API specifications (i.e. netstandard, net452, etc). If support for a new version of Core or Framework require breaking changes on our part, then we'll include those in the next major version of the SDK, too.

I don't have an ETA on when the next major version of this SDK will be released, it is not something we're currently working on now. That said, it is very much on our radar because we do recognize that good library maintenance includes regular updates to support whatever the latest and greatest of that language is.

I'm going to close this issue since there isn't anything actionable for us to address, but if anyone does encounter issues with our SDK while using .NET 6, please create an issue so we can investigate!
