### ISSUE TITLE
Localizing the message of Result object

### ISSUE THREAD

**Issue by Hem-Tark** [braintree/braintree_dotnet#125]
**I am creating this issue as I didn't find any particular platform to ask this question (like a Discussions tab or a community forum).**

### General information

* SDK/Library version: Braintree Dotnet library version _5.12.0_
* Environment: This would affect both Sandbox and Production
* Language, language version, and OS: DotNet _v6_, OS Windows _10_

### Issue description

I am using the Braintree API to process transactions. The `SaleAsync` method returns an object of type Result. The result has a field named `message`. My requirement is to **localize** this message string. Does Braintree provide support for this? If, not what is recommended way of localizing the message from the Result object?

**Comment by Epreuve** [comment]
Hi @Hem-Tark 

We do not currently offer support for localizing the API response that is serialized into the `message` field, and do not have any plans to add it as a feature.  We don't have any specific recommendation if that is something you wish to do as part of your integration.

Be aware that because this field could contain human readable information about any error, it's possible that returning it directly to your payment form could leak implementation details about your integration.
