### ISSUE TITLE
.NET api not secure?

### ISSUE THREAD

**Issue by cdangana** [braintree/braintree_dotnet#14]
The example provided on the first page of this repo worked immediately with no issues but no payment_method_nonce required, so according to the support folks at Braintree, this method is not secure.  Is there a method(s) in this api to securely transfer credit card information?  Is there a method in the api that creates the payment_method_nonce?

**Comment by pblesi** [comment]
Hi @cdangana,

I am a developer at Braintree. The example in this repository's README requires the merchant to obtain higher level of PCI certification because credit card numbers are present on the merchant's server.  Using a `payment_method_nonce` will reduce the PCI burden on behalf of the merchant. 

[Here](https://developers.braintreepayments.com/javascript+dotnet/guides/transactions#sale) is documentation on how to process credit cards using a `payment_method_nonce`. This will require that you use our client SDKs (web, ios, or android) in order to generate a nonce and pass it to your server.

If you need need further help contact our [Support Team](https://support.braintreepayments.com)

Thanks
