### ISSUE TITLE
WebhookKind is not a true Enum so cannot be used in switch

### ISSUE THREAD

**Issue by tofutim** [braintree/braintree_dotnet#30]
It would be nice to be able to do 

```
switch (notification.Kind) {

}
```

but WebhookKind is a custom defined "Enumeration" instead of a true Enum, so this cannot be done.

namespace Braintree
{
    public abstract class Enumeration
    {
        protected string Name;

        protected Enumeration(string name);

        public override string ToString();
    }
}

is it because you are trying to support ALL?

**Comment by pblesi** [comment]
@tofutim 

The underlying representation for an `enum` [must be an integral type](https://msdn.microsoft.com/en-us/library/sbbt4032.aspx) such as an integer, however we use strings as underlying representations of types in order to have them serialized and communicated with our API. 

This is the reason that we have our custom underlying Enumeration type instead of using dotnet's built-in enum type.
