### ISSUE TITLE
Local build - could not find file <GitHub root>\braintreeSgKey.snk

### ISSUE THREAD

**Issue by hughbe** [braintree/braintree_dotnet#37]
1. Clone the repository
2. cd src/Braintree
3. dotnet restore
4. dotnet build

## Expected Behaviour
Build passes

## Actual behaviour
Build fails with the following error (sorry for the screencap!)
![error](https://cloud.githubusercontent.com/assets/1275900/19471562/bf140bf6-951b-11e6-9766-2f36d71a3515.png)

## Solution 
Removing the ```"buildOptions": {
    "keyFile": "../../../braintreeSgKey.snk"
  },``` in the `project.json` file fixes the problem

**Comment by jackellenberger** [comment]
Hi @hughbe,

This is a known behavior of the library and a concession we have had to make in order to publish the Braintree package on NuGet, where we have traditionally reached the most dotnet developers. With that said, multiplatform support in version 3.0.0 means we can't assume that NuGet will be the primary access point anymore. We'll update the library and our deployment script to inject the key requirement at deploy-time and not require it by default in the source.

Your solution is correct. For those running into this error using `xbuild`, a similar solution is to run `sed -i "s/<SignAssembly>true/<SignAssembly>false" src/Braintree/Braintree.xproj`.
