### ISSUE TITLE
Dispute properties missing

### ISSUE THREAD

**Issue by coolkev** [braintree/braintree_dotnet#49]
The dotnet SDK currently includes properties for all of the Dispute fields that are described in the [documentation](https://developers.braintreepayments.com/reference/response/transaction/dotnet#disputes-objects). There are several other properties that are included in the raw Transaction/Disputes API response, but there is no way to access these values.

- amount-won
- case-number
- created-at
- merchant-account-id
- reference-number
- updated-at
- original-dispute
- status-history
  - effective-date
  - status
  - timestamp

I really only need access to updated-at and the status-history values, but might as well include everything.

**Comment by sdcoffey** [comment]
Hey @coolkev,

Thanks for bringing this up. We're wondering why and how you might want to use the values. If we expose them here, we also have to expose them in our other five server SDKs, and want to make sure they will be useful and clear to all of our API consumers. To give you some background, this dispute object is used between some of our internal services, as well as a response object in the SDKs. Since we didn't think merchants would use these additional parameters, we haven't exposed them in the SDKs. Can you give us a brief explanation of how you're intending to make use of these additional fields?

**Comment by EvanHahn** [comment]
We're going to close this due to inactivity, but please feel free to open a new issue if you're still having this problem (or any other problems)!
