### ISSUE TITLE
Cancellation tokens for async gateway methods

### ISSUE THREAD

**Issue by chrisdpratt** [braintree/braintree_dotnet#70]
None of the async gateway methods support cancellation tokens. Was that an intentional design decision?

**Comment by crookedneighbor** [comment]
Since all of the async operations in the SDK involve making an HTTP request to the Braintree API, there isn't really a case where you can cancel the action, because the HTTP request would have still gone through.

Can you explain your use case for cancellation tokens? There may be something I'm overlooking.

**Comment by crookedneighbor** [comment]
I'm going to close this issue for now, since it doesn't seem useful for how this SDK operates, but if I'm missing a use case, feel free to comment here and explain it.
